services:
    php:
        build: ./docker/php
        entrypoint: php artisan octane:frankenphp --max-requests=1
        ports:
            - "3000:3000"
            - "8000:8000"
        volumes:
            - ./src:/app
            - ./docker/caddy/data:/data
            - ./docker/caddy/config:/config
    mariadb:
        build: ./docker/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: base_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/log:/var/log/mysql
    phpmyadmin:
        build: ./docker/phpmyadmin
        ports:
            - 8081:80
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        volumes:
            - /sessions
